services:
  ################
  ## TRIPS API ##
  ################
  bv_trips_api:
    #restart: always #for production only
    container_name: bv_trips_api
    image: node:lts
    volumes:
      - ./trips/api:/usr/src/app
    working_dir: /usr/src/app
    command: npm run dev
    env_file: ./trips/api/.env
    ports:
      - 3333:3000
    networks:
      - bv
    depends_on:
      bv_trips_db:
        condition: service_healthy
    links:
      - bv_trips_db

  ##############
  ## TRIPS DB ##
  ##############
  bv_trips_db:
    #restart: always #for production only
    container_name: bv_trips_db
    image: mariadb
    env_file:
      - ./trips/db/.env
    volumes:
      - ./trips/db/data:/var/lib/mysql
      - ./trips/db/scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./trips/db/scripts/data.sql:/docker-entrypoint-initdb.d/2.sql
    networks:
      - bv
    healthcheck:
      test: '/usr/bin/mysql --user=bv_trips_db --password=password --execute "SHOW DATABASES;"'
      interval: 3s
      timeout: 1s
      retries: 5

  #############
  ## ADMINER ##
  #############
  bv_adminer:
    container_name: bv_adminer
    restart: unless-stopped
    image: adminer
    ports:
      - 8181:8080
    networks:
      - bv
    depends_on:
      - bv_trips_db

networks:
  bv:
    driver: bridge
